export const CLOUD = "yoav-cloud";

export const VIEW_STATES = {
	EXPANDED: "EXPANDED",
	MINIFIED: "MINIFIED",
};

export const FETCH_STATUSES = {
	NONE: "NONE",
	PROGRESS: "PROGRESS",
	FAILED: "FAILED",
};

export const TYPES = {
	SET_PHOTOS: "SET_PHOTOS",

	SET_SELECTED_PHOTO: "SET_SELECTED_PHOTO",

	TOGGLE_VIEW_STATE: "TOGGLE_VIEW_STATE",

	SET_FETCH_STATUS: "SET_FETCH_STATUS",

	FETCH_PHOTOS: "FETCH_PHOTOS",

	SET_EXPOSED_PHOTO: "SET_EXPOSED_PHOTO",

	REMOVE_PHOTO: "REMOVE_PHOTO",

	SET_PHOTOS_PRICES: "SET_PHOTOS_PRICES",

	CLEAR_PHOTOS: "CLEAR_PHOTOS",

	TOGGLE_BIG_PERF_INDICATOR: "TOGGLE_BIG_PERF_INDICATOR",

	FETCH_PHOTO_TRANSFORMATIONS: "FETCH_PHOTO_TRANSFORMATIONS",

	SET_PHOTO_TRANSFORMATION_URL: "SET_PHOTO_TRANSFORMATION_URL",

	SET_PHOTO_TRANSFORMATIONS: "SET_PHOTO_TRANSFORMATIONS",
};